eureka:
    client:
        service-url:
            defaultZone: http://119.23.31.3:8761/eureka,http://120.79.247.111:8761/eureka
jasypt:
    encryptor:
        password: EbfYkitulv73I2p0mXI50JMXoaxZTKJ7
server:
    port: 8088
sftp:
    host: 119.23.31.3
    password: ENC(0shM4ewRFx4BmRLtrBo/q8B07p6djZQ0)
    port: 22
    rootPath: /data/sftp/sftp/upload
    username: sftp
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: ENC(gmyc0w5G9juDFphYmJc/1F1DTg//s+dA)
        url: jdbc:mysql://120.79.247.111:3306/dev_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
        username: root
    redis:
        database: 0
        host: 120.79.247.111
        password: ENC(gmyc0w5G9juDFphYmJc/1F1DTg//s+dA)
        port: 6379
        sentinel:
            nodes: 120.79.247.111:26379,119.23.31.3:26379
    rabbitmq:
        addresses:  120.79.247.111:26379,119.23.31.3:26379
        username: rabbitmq
        password: rabbitmq