server:
  port: 9088
  tomcat: 
    max-connections: 100
    max-threads: 100
    min-spare-threads: 30
    accept-count: 5000
spring.application.name: Xyf-ProxyService

logging.level.com.xinyunfu.mapper: debug
eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
  client:
    registryFetchIntervalSecondes: 15
    service-url:
      defaultZone: http://192.168.1.56:8761/eureka,http://192.168.1.56:8762/eureka,http://192.168.1.56:8763/eureka

feign.client.config.default.connect-timeout: 5000
feign.client.config.default.read-timeout: 5000    
logging.level.org.springframework.web.servlet.DispatcherServlet: DEBUG

spring:
  datasource: 
      #默认此处应该是数据的sid  
      cm:   
         driver-class-name: com.mysql.cj.jdbc.Driver 
         jdbcUrl: jdbc:mysql://localhost:3306/cm?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
         username: root
         password: 
      om:
         driver-class-name: com.mysql.cj.jdbc.Driver 
         jdbcUrl: jdbc:mysql://localhost:3306/om?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=UTC
         username: root
         password: 

