server:
  port: 9088
  tomcat: 
    max-connections: 100
    max-threads: 100
    min-spare-threads: 30
    accept-count: 5000
spring.application.name: OrderTree

logging.level.com.xinyunfu.mapper: debug

spring:  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/otree?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 
  free: 
    button: take_on
  redis:
    sentinel:
      nodes: 120.79.247.111:26379,119.23.31.3:26379
      master: mymaster 
    password: ENC(gmyc0w5G9juDFphYmJc/1F1DTg//s+dA)
    database: 0 
    port: 6379
    jedis:
      pool:
        max-idle: 10
        min-idle: 0
        max-active: -1
        max-wait: -1
    host: 120.79.247.111
    ssl: false
    timeout: 600

jasypt:
  encryptor:
    password: EbfYkitulv73I2p0mXI50JMXoaxZTKJ7

  
eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
  client:
    registryFetchIntervalSecondes: 15
    service-url:
      defaultZone: http://192.168.1.56:8761/eureka,http://192.168.1.56:8762/eureka,http://192.168.1.56:8763/eureka

feign.client.config.default.connect-timeout: 5000
feign.client.config.default.read-timeout: 5000    
logging.level.org.springframework.web.servlet.DispatcherServlet: DEBUG
logging.level.org.springframework: INFO