spring.application.name: Gateway
server:
  port: 8080
  tomcat: 
     max-connections: 300
     max-threads: 150
     min-spare-threads: 40
     accept-count: 30000     
eureka:
  client:
    registry-fetch-interval-seconds: 15
    service-url.defaultZone: http://119.23.31.3:8761/
zuul: 
  ribbon-isolation-strategy: thread
  ignored-services: E-Bank,OrderTree
  host:
    connect-timeout-millis: 30000  #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 30000   #socket超时
    max-per-route-connections: 400
    max-total-connections: 60
  routes:
     CustomerManage: /CustomerManage/**
     ProductManage: /ProductManage/**
     OrderManage: /OrderManage/**
     QuestionBank: /QuestionBank/**
     VolumeMarket: /VolumeMarket/**    
#login of token timeout,second
login.token.timeout: 12000
handler.req.url: /CustomerManage/customer/user/password/code
handler.req.time: 3000
handler.encry.key: MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAJBDWIPaOUu0UVgeHChPWdcE0LoejY3kpFI6RYjrYFBGCyFiYmkhxOpm4m2t5mHjDvU8bjcrL0y41bpEnzoQwLH86L8wFiSnO5VlcZ4IA8S/u1PU6bT53AzNww/j2eZFiWGeGy3rzKXzcbMF1ZWpC83rH4XFZZ6SzMbU8sAdfRm1AgMBAAECgYANT5l4OQd2W8Hxrn2Mnp28gD4+HhmTkRg0WhoWYxl07rGSOAC6kJoZwrp7wkLynz+/Ev9caciofJmD4VcLxYXyAtwXVK57tcKwC7xrKF/fJrQtZKJUngbj6KkpJKT7cCGR0t+PNY5rh63l8C87xrqZrKRUsjPpoFxMQ5EZ5eyWIQJBAMEcqC0GewrD5nT4tme7SeXRgWdkARsTPzzXktHU/As7Ro9dYozkErVVa91K8JHp4nEFXfz5U/c5ZGuCtSqafu0CQQC/PkJqPVNScvM1NGlDx6HRQ1tDPcPF6Yfb+ho575MY8dwLVp7UUbtUZyR7gtCHF74KjJKdLFSWVFI0CaguF2TpAkAFkC3IHketJ7eb5w5aLqsSU9bGg7sEbKmFtzAjm18nc620s5wDMw7W6n8RAPetPG+pkd4DS6t/k8ew0TMm5wyBAkBQ7LOF6TVc6i9oECmK+OrMdkgkB/rTwKIwv4Bhi7MfFxkZ4ymKhptSd+LEMPK0d6N/K0TPJXcVtdCjHIMCHfwhAkBHosjFbPw+CMr7rWCScHV+tfFyd1Qcc2MdhBeL4wRv4aMwLWoF8A1a5+zaPEbZ1Ic5y7fz24nkrLgzAMDCzgupdf723820
handler.auth.md5.key: xyf1.0.0
auth.isOn.takeOn: start
# 验证白名单
token.white.list: /VolumeMarket/couponManger/queryCanBuyCou,/CustomerManage/customer/user/register,/CustomerManage/customer/user/login,/ProductManage,/CustomerManage/customer/common/code,/CustomerManage/customer/user/password/code
xyf.api.version: 1.0.0
#redis 哨兵模式配置
spring.redis.host: xingyunfu.redis.com
# 启用SSL支持。
spring.redis.port: 6379
spring.redis.password: xyfRedis
spring.redis.database: 0 

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
            
ribbon: 
  ConnectTimeout: 1000
  ReadTimeout: 10000
  OkToRetryOnAllOpertions: false
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  
            