CREATE TABLE `inner_acct_manger` (
  `id`                  int(11)             NOT NULL AUTO_INCREMENT,
  `acc_no`              varchar(30)                             COMMENT '账号',
  `acc_name`            varchar(200)                            COMMENT '账号名',
  `bank_name`           varchar(200)                            COMMENT '银行名称',
  `bank_no`             varchar(30)                             COMMENT '银行编号',
  `balance`             decimal(30,2)       DEFAULT '0.00'      COMMENT '余额',
  `freezing_balance`    decimal(30,2)       DEFAULT '0.00'      COMMENT '冻结余额',
  `can_user_balance`    decimal(30,2)       DEFAULT '0.00'      COMMENT '可用余额',
  `user_id`             varchar(30)                             COMMENT '用户ID',
  `acc_type`            char(20)                                COMMENT '账户类型',
  `busi_status`         varchar(30)                             COMMENT '业务状态',
  `enable`              tinyint(2)          DEFAULT '1'         COMMENT '是否可用（可用=1，禁用=0）',
  `id_card_no`          varchar(20)                             COMMENT '身份证号码',
  `branch_name`         varchar(200)                            COMMENT '分行名称',
  `branch_no`           varchar(100)                            COMMENT '分行行号',
  `province_name`       varchar(200)                            COMMENT '省份',
  `city_name`           varchar(100)                            COMMENT '城市',
  `user_name`           varchar(200)                            COMMENT '用户姓名',
  `created_date`        timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by`          varchar(50) NOT NULL DEFAULT 'admin'    COMMENT '创建人',
  `updated_date`        timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `updated_by`          varchar(50) NOT NULL DEFAULT 'admin'    COMMENT '最后修改人',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8