CREATE TABLE `transaction_recv_log` (
  `id`                  int(30)         NOT NULL AUTO_INCREMENT,
  `merchant_no`         varchar(20),
  `subject`             varchar(200)                                COMMENT '主题',
  `out_trade_no`        varchar(20)                                 COMMENT '外部订单号',
  `amount`              decimal(16,0)                               COMMENT '支付金额',
  `dealtime`            date                                        COMMENT '订单成交时间，',
  `private_value`       varchar(20)                                 COMMENT '私有值',
  `pay_type`            int(11)                                     COMMENT '支付方式',
  `status`              int(11)                                     COMMENT '当前订单状态',
  `settle_amount`       decimal(16,0)                               COMMENT '结算金额',
  `fee`                 decimal(10,0)                               COMMENT '手续费',
  `version`             char(20)                                    COMMENT '版本',
  `sys_order_no`        varchar(20)                                 COMMENT '支付系统单号',
  `create_time`         date                                        COMMENT '订单创建时间',
  `channel_type`        int(11)                                     COMMENT '通道类型',
  `voucher`             varchar(20)                                 COMMENT '交易凭证号',
  `enable`              int(2)              DEFAULT '1'             COMMENT '1有效0无效',
  `created_date`        date,
  `created_by`          varchar(20),
  `updated_date`        date,
  `updated_by`          varchar(20),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='转账交易->结果返回'