CREATE TABLE `transaction_send_log` (
  `id`                      int(30)             NOT NULL AUTO_INCREMENT     COMMENT 'Id',
  `subject`                 varchar(200)                                    COMMENT '交易主题',
  `private_value`           varchar(20)                                     COMMENT '私有值',
  `merchant_no`             varchar(30)                                     COMMENT '商户号',
  `amount`                  decimal(18,2)                                   COMMENT '金额',
  `order_no`                varchar(30)                                     COMMENT '订单号',
  `bank_name`               varchar(200)                                    COMMENT '银行名称',
  `branch_name`             varchar(200)                                    COMMENT '支行联行名称',
  `branch_no`               varchar(30)                                     COMMENT '支行联行号',
  `car_no`                  varchar(20)                                     COMMENT '卡号',
  `channel_type`            int(4)                                          COMMENT '通道类型',
  `id_card_no`              varchar(20)                                     COMMENT '持卡人身份证',
  `user_name`               varchar(200)                                    COMMENT '持卡人名称',
  `bank_code`               varchar(50)                                     COMMENT '银行简码，例如工商银行=ICBC，招商银行=CMB',
  `city_name`               varchar(20)                                     COMMENT '城市',
  `province_name`           varchar(20)                                     COMMENT '省份',
  `pay_type`                int(11)                                         COMMENT '支付方式，',
  `return_url`              varchar(200)                                    COMMENT '前端返回地址，',
  `notify_url`              varchar(200)                                    COMMENT '异步通知地址',
  `death_time`              date                                            COMMENT '订单过期时间，',
  `sub_channel`             char(10)                                        COMMENT '子渠道',
  `trade_type`              char(1)                                         COMMENT '交易类型，二维码 1 JSAPI 2 H5 4 APP 8 付款码 16',
  `auth_code`               varchar(50)                                     COMMENT '授权码，付款码扫描结果字符串 返',
  `enable`                  int(11)             DEFAULT '1'                 COMMENT '1为有效0无效',
  `channel`                 char(20)                                        COMMENT '渠道',
  `created_date`            date,
  `created_by`              varchar(200),
  `updated_date`            date,
  `updated_by`              varchar(200),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=222 DEFAULT CHARSET=utf8 COMMENT='交易发送记录->发送到支付平台'