eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.101:8761/eureka,http://192.168.1.101:8762/eureka,http://192.168.1.101:8763/eureka
jasypt:
    encryptor:
        password: EbfYkitulv73I2p0mXI50JMXoaxZTKJ7
server:
    port: 8080
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: ENC(gmyc0w5G9juDFphYmJc/1F1DTg//s+dA)
        url: jdbc:mysql://192.168.1.24:3306/volume_market?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
        username: root
    rabbitmq:
        #非集群模式下，填写MQ服务器的地址和端口 
        addresses: 120.79.247.111:5672,119.23.31.3:5672
        connection-timeout: 15000
        listener:
            simple:
                acknowledge-mode: manual
                concurrency: 1
                max-concurrency: 5
                prefetch: 1
        # rabbitmq的用户名和密码        
        username: admin
        password:  ENC(s96SQqGVBurvS+tvPIKleVYmDUpwCtGm)
        publisher-confirms: true
        publisher-returns: true
        template:
            mandatory: true
    redis:
        database: 0
        host: 120.79.247.111
        password: ENC(gmyc0w5G9juDFphYmJc/1F1DTg//s+dA)
        port: 6379
        #sentinel:
         #   nodes: 120.79.247.111:26379,119.23.31.3:26379       
    jackson:
      date-format: yyyy-MM-dd
      time-zone: GMT+8
sftp:
    host: 119.23.31.3
    password: ENC(0shM4ewRFx4BmRLtrBo/q8B07p6djZQ0)
    port: 22
    rootPath: /data/sftp/sftp/upload
    username: sftp     
    
#熔断器启用
feign.hystrix.enabled: true
feign.client.config.default.loggerLevel: full
hystrix.command.default.execution.timeout.enabled: true
#断路器的超时时间,下级服务返回超出熔断器时间，即便成功，消费端消息也是TIMEOUT,所以一般断路器的超时时间需要大于ribbon的超时时间。
#服务的返回时间大于ribbon的超时时间，会触发重试
##默认=1000，太小
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
#ribbon请求连接的超时时间- 限制3秒内必须请求到服务，并不限制服务处理的返回时间
ribbon.ConnectTimeout: 3000
#请求处理的超时时间 下级服务响应最大时间,超出时间消费方（路由也是消费方）返回timeout
ribbon.ReadTimeout: 5000
logging.level.org.springframework.web.servlet.DispatcherServlet: DEBUG
logging.level.org.springframework: INFO