# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 3.4.0
  # 版权年份
  copyrightYear: 2019
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: D:/ruoyi/uploadPath
  # 获取ip地址开关
  addressEnabled: true



#注册中心配置
eureka:
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipaddress}:${server.port}
  client:
    registry-fetch-interval-seconds: 5
feign:
  hystrix:
    enabled: false


# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
 
# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5

# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  redis:
    sentinel:
      master: mymaster
    jedis:
      pool:
        max-idle: 10
        min-idle: 0
        max-active: -1
        max-wait: -1
    ssl: false
    timeout: 600
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: dev
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
  
eureka:
  client:
    service-url:
      defaultZone: http://xingyunfu.eureka.com:8761/eureka,http://xingyunfu.eureka.com:8762/eureka,http://xingyunfu.eureka.com:8763/eureka


# 数据源配置
spring:
#    datasource:
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        password: ENC(gmyc0w5G9juDFphYmJc/1F1DTg//s+dA)
#        url: jdbc:mysql://192.168.1.56:3306/ProductManage?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
#        username: root
  redis:
    database: 8
    host: xingyunfu.redis.com
    password: xyfRedis
    port: 6379
  datasource:
     type: com.alibaba.druid.pool.DruidDataSource
     driverClassName: com.mysql.cj.jdbc.Driver
     druid:
         # 主库数据源
         master:
             url: jdbc:mysql://xingyunfu.mysql.com:3306/vm?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
#                  url: jdbc:mysql://192.168.1.24/supplychain?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
             username: xyf.root
             password: root321!
         # 从库数据源
         slave:
             # 从数据源开关/默认关闭
             enabled: false
             url:
             username:
             password:
         # 初始连接数
         initialSize: 5
         # 最小连接池数量
         minIdle: 10
         # 最大连接池数量
         maxActive: 20
         # 配置获取连接等待超时的时间
         maxWait: 60000
         # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
         timeBetweenEvictionRunsMillis: 60000
         # 配置一个连接在池中最小生存的时间，单位是毫秒
         minEvictableIdleTimeMillis: 300000
         # 配置一个连接在池中最大生存的时间，单位是毫秒
         maxEvictableIdleTimeMillis: 900000
         # 配置检测连接是否有效
         validationQuery: SELECT 1 FROM DUAL
         testWhileIdle: true
         testOnBorrow: false
         testOnReturn: false
         webStatFilter:
             enabled: true
         statViewServlet:
             enabled: true
             # 设置白名单，不填则允许所有访问
             allow:
             url-pattern: /druid/*
             # 控制台管理用户名和密码
             login-username:
             login-password:
         filter:
             stat:
                 enabled: true
                 # 慢SQL记录
                 log-slow-sql: true
                 slow-sql-millis: 1000
                 merge-sql: true
             wall:
                 config:
                     multi-statement-allow: true 
  
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.ruoyi
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml




# PageHelper分页插件
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 

# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain: 
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
    # 同一个用户最大会话数，比如2的意思是同一个账号允许最多同时两个人登录（默认-1不限制）
    maxSession: -1
    # 踢出之前登录的/之后登录的用户，默认踢出之前登录的用户
    kickoutAfter: false

# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

## 阿里云存储
alioss:
  endpoint: oss-cn-shenzhen.aliyuncs.com  #EndPoint（地域节点）
  accessKeyId: LTAIVgPTngg9CemW          #阿里云主账号AccessKey
  acceaccessKeySecret: CLsYpujPEce3sSGWUhidbKeENEFgoW #对应的accessKeySecret
  bucketName:  xyf888
  productPath:   product/details
  productBanner:   product/banner
  productVoideDetails:   product/video/details
  homeBanner:   home/banner
  homeNumu:   home/menu
  homeCategory: category/menu
  userAvatar: user/avatar
  baseHost: http://images.xyf823.com/
  


eureka:
  client:
    service-url:
      defaultZone: http://xingyunfu.eureka.com:8761/eureka,http://xingyunfu.eureka.com:8762/eureka,http://xingyunfu.eureka.com:8763/eureka

