eureka:
  client:
    service-url:
      defaultZone: http://120.79.247.111:8761/eureka/,119.23.31.3:8761/eureka/
jasypt:
    encryptor:
        password: EbfYkitulv73I2p0mXI50JMXoaxZTKJ7
server:
    port: 8085
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: ENC(gmyc0w5G9juDFphYmJc/1F1DTg//s+dA)
        url: jdbc:mysql://120.79.247.111:3306/volume_market?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
        username: root
    rabbitmq:
        #非集群模式下，填写MQ服务器的地址和端口 
        addresses: 120.79.247.111:5672,119.23.31.3:5672
        connection-timeout: 15000
        listener:
            simple:
                acknowledge-mode: manual
                concurrency: 1
                max-concurrency: 5
                prefetch: 1
        # rabbitmq的用户名和密码        
        username: admin
        password:  ENC(s96SQqGVBurvS+tvPIKleVYmDUpwCtGm)
        publisher-confirms: true
        publisher-returns: true
        template:
            mandatory: true

sftp:
    host: 119.23.31.3
    password: ENC(0shM4ewRFx4BmRLtrBo/q8B07p6djZQ0)
    port: 22
    rootPath: /data/sftp/sftp/upload
    username: sftp     
