eureka:
  client:
    service-url:
      defaultZone: http://120.79.247.111:8761/eureka/,119.23.31.3:8761/eureka/
jasypt:
  encryptor:
    password: EbfYkitulv73I2p0mXI50JMXoaxZTKJ7
server:
  port: 8083
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ENC(gmyc0w5G9juDFphYmJc/1F1DTg//s+dA)
    url: jdbc:mysql://120.79.247.111:3306/InfoCenter?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
  redis:
    database: 0
    host: 120.79.247.111
    password: ENC(gmyc0w5G9juDFphYmJc/1F1DTg//s+dA)
    port: 6379
    sentinel:
      master: mymaster
      nodes: 120.79.247.111:26379,119.23.31.3:26379
  rabbitmq:
    #非集群模式下，填写MQ服务器的地址和端口
    addresses: 120.79.247.111:5672,119.23.31.3:5672
    connection-timeout: 15000
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 5
        prefetch: 1
    # rabbitmq的用户名和密码
    username: admin
    password:  ENC(s96SQqGVBurvS+tvPIKleVYmDUpwCtGm)
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
logging:
  level:
    com:
      xinyunfu: INFO
  path: "/logs/infoCenter"

sftp:
  host: 119.23.31.3
  password: ENC(0shM4ewRFx4BmRLtrBo/q8B07p6djZQ0)
  port: 22
  rootPath: /data/sftp/sftp/upload
  username: sftp
send-message:
  base-url: http://api.sms.yx18g.cn
  merchant-no: XYF166668888
  merchant-no-Key: 354c35183e7c4e85bdf88fdfb079be2b
info-center:
  push:
    short-message: 18e7ed080a0d0081acb9b4e2bd913c25
    push-message: 6f08ccd66fcfbf828814962055b190fc
    wechat-message: 38ad8d3c312c9ff343dd4d84c3324ff5
    # 商户号
    merchant-no: ${send-message.merchant-no}
    # 密钥
    merchant-no-Key: ${send-message.merchant-no-Key}
    # 请求地址
    push-url: http://api.msg.yx18g.cn/send/index?MerchantNo={MerchantNo}&Data={Data}&Sign={Sign}
    # 自定义短信内容
    message-custom: http://api.msg.yx18g.cn/sms/Send?MerchantNo={MerchantNo}&Data={Data}&Sign={Sign}
